#!/bin/sh
pkg update -y
if [ -z "$ZSH" ]; then
  pkg install zsh -y
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
pkg install -y \
  vim \
  openssh \
  rsync
termux-reload-settings

[ ! -d "$HOME/storage" ] && termux-setup-storage